### ISSUE TITLE
allow knative users to provide registry credentials to a knative build

### ISSUE THREAD

**Issue by ekcasey** [buildpack/roadmap#53]
[placeholder]

**Comment by trisberg** [comment]
This is the error in `build-step-analyze` container:

```
[build-step-analyze]: 2019/03/06 18:43:54 Error: connect to repo store 'gcr.io/cf-sandbox-trisberg/square:minikube': Get https://gcr.io/v2/token?scope=repository%3Acf-sandbox-trisberg%2Fsquare%3Apull&service=gcr.io: invoking docker-credential-gcr: exit status 1; output: docker-credential-gcr/helper: could not retrieve GCR's access token: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

**Comment by trisberg** [comment]
This is the Knative service:

```
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: hello-knative
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: cnb-build
          source:
            git:
              revision: master
              url: https://github.com/trisberg/hello-knative.git
          template:
            arguments:
            - name: IMAGE
              value: gcr.io/cf-sandbox-trisberg/hello-knative:cnb
            - name: BUILDER_IMAGE
              value: "packs/samples:v3alpha2"
            - name: RUN_IMAGE
              value: "packs/run:v3alpha2"
            kind: BuildTemplate
            name: buildpacks-cnb
      revisionTemplate:
        spec:
          container:
            image: gcr.io/cf-sandbox-trisberg/hello-knative:cnb
```

and the `cnb-build` service account has the secret with the GCR credentials to be able to push images. Same build works fine on GKE.
